### ISSUE TITLE
Create Reusable Search Bar Component with API Console Log

### ISSUE THREAD

**Issue by Stuartwastaken** [oss-slu/lrda_website#13]
### Issue Details:
Create a search bar component in `components` folder. Style with Tailwind CSS. On search click, console log the output from the API service class using the search bar's text and "Yash Bhatia" as the user.

#### Technical Requirements:

1. `SearchBar.tsx` in `components`.
2. Style with Tailwind.
3. Console log API service class output on search.

### Acceptance Criteria:

1. Exists in `components`.
2. Styled with Tailwind.
3. Console logs API output on search.

**Comment by Josh-Hogan-87** [comment]
Search bar in the components folder is imported in the page.tsx class. However when trying to render the search bar the webpage could not compile(react state management issue).

- error ./app\components\searchBar.tsx
ReactServerComponentsError:

You're importing a component that needs useState. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

   ,-[C:\Users\17156\CSCI4961\lrda_website\app\components\searchBar.tsx:1:1]
 1 | import React, { useState } from 'react';
   :                 ^^^^^^^^
 2 | import ApiService from './ApiService';
 3 |
 3 |
   `----

Maybe one of these should be marked as a client entry with "use client":
  ./app\components\searchBar.tsx
  ./app\layout.tsx

This error would appear in the terminal and on the webpage. Requires further troubleshooting.

**Comment by Stuartwastaken** [comment]
I saw that you were having issues with compiling and importing the files so I just imported the files and fixed up the issues. Then we had other render issues from an old layout.tsx so I cleaned up that file. So now search works and it console logs so this issue is actually finished and ready to be merged into main.
