### ISSUE TITLE
Full Team Meeting

### ISSUE THREAD

**Issue by izakrobles** [oss-slu/lrda_website#26]
#### Description:

In order to kickstart the implementation of our webpage this semester, it's crucial that we have a full team meeting to decide on the various details surrounding this task. The meeting will include team members Stuart Ray, Yash Bhatia, Josh Hogan, and Izak Robles, with Dr. Adam Park as the product owner.

#### Agenda:
- Reviewing the current status of the lrda_website project.
- Discussing and deciding on the design and functional requirements of the webpage.
- Setting up a timeline and assigning responsibilities for the implementation phase.
- Addressing any concerns or questions from the team.

#### Proposed Date and Time:
- Date: 10/11/2023
- Time: 7PM
- Duration: Approximately 4 hours

#### Participants:
- @Stuartwastaken 
- @yashb196 
- @Josh-Hogan-87 
- @izakrobles 
- Dr. Adam Park

#### Pre-Meeting Preparation:
- Please review the current project repository and come with any questions or suggestions.
- Consider any design or functional preferences you have for the webpage.

**Comment by Stuartwastaken** [comment]
We had a productive meeting with Dr. Adam Park
