### ISSUE TITLE
Register button

### ISSUE THREAD

**Issue by Stuartwastaken** [oss-slu/lrda_website#34]
### Issue Details
Create a register button that visually matches the existing login button. This button does not need to have any functionality; it is purely for visual purposes at this stage.

#### Technical Requirements
1. Create a new TypeScript file called `register_button.tsx` in the `components` folder.
2. In the `register_button.tsx` file, design the button to visually match the existing `login_button.tsx`.
3. Use Next.js 13 and any necessary CSS for styling.

#### Acceptance Criteria
1. A `register_button.tsx` file exists in the `components` folder.
2. The register button visually matches the login button as per design specifications.
3. The button does not require any functional logic for user registration at this stage.

#### Issue Context
This issue pertains to the creation of a register button for future user registration functionalities. At this stage, the focus is on the visual design to ensure it aligns with the existing login button. This prepares the UI for future enhancements that will include registration capabilities.

**Comment by Josh-Hogan-87** [comment]
Register but has been created, added to the login page, and the branch has been merged into main. Issue completed.
