### ISSUE TITLE
Responsive Design Implementation

### ISSUE THREAD

**Issue by yashb196** [oss-slu/lrda_website#4]
Issue:

To ensure the website is accessible across various device types (desktop, tablet, mobile), the design should be responsive. Using Tailwind CSS, we need to ensure that components adjust and display properly across varying screen sizes.

Acceptance Criteria:

The website should display correctly on desktop, tablet, and mobile views.
Tailwind CSS's responsive utilities should be utilized to adjust styles based on the device's viewport size.
There should be no horizontal scrolling on any standard device.

**Comment by Stuartwastaken** [comment]
This is something we can do throughout the build process as we tackle each issue. Impossible to do this issue in one foul sweep and I think we're all responsible for this.
