### ISSUE TITLE
Search Functionality for Notes

### ISSUE THREAD

**Issue by yashb196** [oss-slu/lrda_website#5]
Issue:

With a potentially growing number of notes, users should be able to quickly locate specific notes. Implementing a search functionality will help users retrieve information more efficiently.

Acceptance Criteria:

A search bar should be available in an accessible location on the UI.
Typing into the search bar should yield real-time results, filtering notes based on the query.
Search should take into account note content and associated tags or labels.
Remember that these issues are drafted based on the provided context and assumptions about the potential features and requirements of your website. They might need fine-tuning based on the actual specifications of your project.

**Comment by Josh-Hogan-87** [comment]
Attached are draft versions of code for the search bar. I will also need to decide and consult the team on the data structure to be used to store this information. Finally, I need to get the with rest of the team as soon as possible so they can run through and explain the code to me. The team should be able to give me a rundown on 9/18/2023 or at our earliest convenience.

[Draft_searchBar_code.txt](https://github.com/oss-slu/lrda_website/files/12644372/Draft_searchBar_code.txt)

[Example_searchLogic.txt](https://github.com/oss-slu/lrda_website/files/12644373/Example_searchLogic.txt)
