### ISSUE TITLE
Create the map page

### ISSUE THREAD

**Issue by izakrobles** [oss-slu/lrda_website#59]
### Issue Details
Develop and implement a UI for the map navigation feature. This includes adding a link in the navigation bar that directs users to a map page. The map page, for the current scope, should display a basic, interactive map that supports zooming and panning but does not require additional functionalities.

#### Technical Requirements
1. Add a new file named `map_page.tsx` in the `src/lib/pages` folder.
2. In `map_page.tsx`, implement a UI that features:
    - A link in the navigation bar that directs to the map page.
    - An interactive map that allows users to zoom in and out and pan across different areas.
3. Ensure the map page is responsive and renders correctly on various screen sizes, keeping in line with the application's overall design and user experience principles.

#### Acceptance Criteria
1. A `map_page.tsx` file exists in the `src/lib/pages` folder.
2. The navigation bar contains a link that navigates to the map page.
3. The map page displays an interactive map which users can zoom and pan across.
4. The map page's UI is responsive and maintains its layout and functionality across different devices and screen sizes.
5. The design and functionality of the map page are consistent with the application's overall theme and user experience guidelines.

Issue:
The addition of a map navigation feature is integral for enhancing user interaction and engagement within the application. The map page, accessible via a link in the navbar, aims to provide a foundational interactive map experience. This initial implementation focuses on basic map interactions like zooming and panning, setting the stage for future enhancements and functionalities.

**Comment by Stuartwastaken** [comment]
Added more features like image rendering, note markers, and search functionality. Plus note markers are clickable with a notecard component
