### ISSUE TITLE
Media Integration

### ISSUE THREAD

**Issue by izakrobles** [oss-slu/lrda_website#62]
### Issue Details
Implement a feature for users to upload and view media, including images and videos, within the application. The media files should be uploaded to the Amazon AWS S3 Bucket via an S3 proxy. Additionally, provide functionalities for users to interact with their media on the page, such as zooming in on photos and controlling video playback.

#### Technical Requirements
1. Develop a media upload functionality in the application that allows users to upload images and videos.
2. Integrate with Amazon AWS S3 Bucket through an S3 proxy to store the uploaded media securely.
3. Implement a feature on the page for users to view their uploaded media.
4. For photos, enable a click-to-zoom feature allowing users to enlarge and closely examine images.
5. For videos, incorporate video controls that include play, pause, and scrubbing through the video timeline.

#### Acceptance Criteria
1. Users can upload both images and videos within the application.
2. Uploaded media is securely stored in the Amazon AWS S3 Bucket via the S3 proxy.
3. Users can view their uploaded images and videos on a designated page in the application.
4. Clicking on an image allows the user to zoom in and out for a detailed view.
5. Video files have playback controls enabling users to play, pause, and scrub through the video.
6. The media viewing and interaction experience is seamless and integrates well with the overall application design and user interface.

Issue:
The integration of an image and video upload feature addresses the need for enhanced user engagement and content sharing within the application. By allowing users to upload and interact with their media, the application becomes more dynamic and user-centric. The secure storage of media using Amazon AWS S3 Bucket and the provision of intuitive media interaction capabilities (zoom for images and playback controls for videos) are crucial for a robust and engaging user experience.

**Comment by Stuartwastaken** [comment]
working on this within the branch of 58-note-component-redesign

**Comment by Stuartwastaken** [comment]
This was finished and a new issue will need to be opened for just video integration, but since we are using tiptap headless, that has youtube support. The head we are using is "mui-tiptap" and that doesn't have video support.
