### ISSUE TITLE
Note component bugs

### ISSUE THREAD

**Issue by Stuartwastaken** [oss-slu/lrda_website#67]
You can cmd + z and it will bring back the previous notes information after selecting multiple notes
** Resolved **

**Comment by izakrobles** [comment]
This may be a new development, but the new location changes does not seem to be saving.

**Comment by Stuartwastaken** [comment]
Location component isn't updating the location even when allowed on safari

Title in the sidebar needs to be truncated

Title needs to be flagged to "Untitled Note"

Title also can be the first few words of the body text if there is no title given
