### ISSUE TITLE
Enhance Save Functionality in Note Component

### ISSUE THREAD

**Issue by yashb196** [oss-slu/lrda_website#72]
#### Objective
Implement an onSave function for the save button in the `note_component` file, ensuring it utilizes `ApiService.overwriteNote` or `ApiService.writeNewNote` appropriately. This function will determine if a new note is being added or an existing note is being edited, and save accordingly.

#### Background
The current UI's save button lacks a definitive saving mechanism. There's a need to establish a clear and effective saving process, whether the user is creating a new note or editing an existing one. This process should seamlessly integrate with the overall note-taking functionality.

#### Technical Requirements
- Add an onSave function within the `note_component` file.
- Implement logic to distinguish between adding a new note and editing an existing note, possibly using a boolean flag.
- Utilize `ApiService.overwriteNote` for editing existing notes and `ApiService.writeNewNote` for adding new notes accordingly.
- Ensure the functionality integrates seamlessly with the UI and the overall note application workflow.

#### Expected Outcome
With the enhanced save functionality:
- Users should be able to save new notes or edit existing ones without issues.
- The application correctly identifies the context (new or existing note) and uses the appropriate API service method.
- The UI reflects the save action smoothly and updates accordingly.

#### Acceptance Criteria
- The onSave function is implemented and operational within the `note_component`.
- The application accurately determines whether a note is new or existing and saves using the correct method.
- The save functionality should be robust, handling edge cases and errors gracefully.
- The component's functionality, including the new save feature, is fully tested and documented.

#### Files to be Modified
- `note_component`

#### Additional Notes
Ensure that the saving mechanism is efficient and user-friendly, fitting well with the existing design and functionality of the note-taking application. Consider any potential edge cases or errors users might encounter and handle these smoothly to maintain a seamless user experience.

### Action Items
- [x] Assign a developer to address the issue.
- [x] Implement the onSave functionality as per the requirements.
- [x] Review and test the new save feature.
- [ ] Merge the changes after approval.

**Comment by Stuartwastaken** [comment]
This is finished just needs merged, for now we are merging all changes into deliverable-2 branch to be merged into main later
