### ISSUE TITLE
Integrate Delete Functionality with API Service in Note Component

### ISSUE THREAD

**Issue by yashb196** [oss-slu/lrda_website#73]
#### Objective
Modify the `note_component` to ensure the delete button calls `ApiService.deleteNoteFromAPI`, effectively deleting the current note from the API upon user action.

#### Background
The note component currently lacks direct integration with the API for deleting notes. Users need a reliable and immediate way to delete notes, and this should be handled through the `ApiService.deleteNoteFromAPI` method to ensure consistency and reliability across the application.

#### Technical Requirements
- Identify and modify the delete function or button event in the `note_component`.
- Integrate the `ApiService.deleteNoteFromAPI` method into the delete functionality.
- Ensure that the delete action is confirmed before executing to prevent accidental deletion.
- Update any relevant state or UI components to reflect the deletion of the note.

#### Expected Outcome
After the integration:
- Users will be able to delete notes, with the action directly interacting with the API.
- The application will reflect the deletion immediately, removing the note from the user interface.
- The overall user experience of note management will be more cohesive and reliable.

#### Acceptance Criteria
- The delete button in the `note_component` successfully calls `ApiService.deleteNoteFromAPI`.
- The application confirms deletion with the user before permanently removing the note.
- Deletion of a note is reflected in the application immediately after the user confirms.
- The delete functionality is robust, handling any potential errors or issues smoothly.

#### Files to be Modified
- `note_component`

#### Additional Notes
As deletion is a critical functionality with permanent consequences, ensure that the user experience is clear and that there are safeguards against accidental deletions. Consider implementing a confirmation dialogue or a temporary "undo" option to enhance user control and prevent unintended loss of data.

### Action Items
- [x] Assign a developer to address the issue.
- [x] Implement the delete functionality integration as per the requirements.
- [x] Review and test the new delete feature.
- [ ] Merge the changes after approval.

**Comment by Stuartwastaken** [comment]
This is finished just needs merged, for now we are merging all changes into deliverable-2 branch to be merged into main later
